name: Deploy to Lambda
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v4
      - name: Deploy code to Lambda
        uses: NicPWNs/py-lambda-action@v1.0.9
        with:
          lambda_layer_arn: "arn:aws:lambda:us-east-1:087441767329:layer:lambda_deps"
          lambda_function_name: "github-discord-event-handler"
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: "us-east-1"
  build:
    needs: deploy
    if: needs.deploy.result == 'success'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v4
      - name: Install Python 3
        uses: actions/setup-python@v5
        with:
          python-version: 3.11
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Register slash commands with Discord
        id: register
        env:
          DISCORD_TOKEN: ${{ secrets.DISCORD_TOKEN }}
          APP_ID: ${{ secrets.DISCORD_APP_ID }}
        run: |
          python register_commands.py
